/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro_pojos;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class AccountGroup extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 790871125086174967L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AccountGroup\",\"namespace\":\"com.sephora.dataplatform.avro\",\"fields\":[{\"name\":\"group_id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"accounts\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Account\",\"fields\":[{\"name\":\"is_merged_with_anonymous_by_card\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"is_anonymous\",\"type\":\"boolean\",\"default\":false},{\"name\":\"group_id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"usa_id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"card_numbers\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":[]},\"default\":[]},{\"name\":\"historical_group_ids\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":[]},\"default\":[]}]},\"default\":[]},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AccountGroup> ENCODER =
      new BinaryMessageEncoder<AccountGroup>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AccountGroup> DECODER =
      new BinaryMessageDecoder<AccountGroup>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AccountGroup> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AccountGroup> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AccountGroup> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AccountGroup>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AccountGroup to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AccountGroup from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AccountGroup instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AccountGroup fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public String group_id;
  @Deprecated public java.util.List<Account> accounts;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AccountGroup() {}

  /**
   * All-args constructor.
   * @param group_id The new value for group_id
   * @param accounts The new value for accounts
   */
  public AccountGroup(String group_id, java.util.List<Account> accounts) {
    this.group_id = group_id;
    this.accounts = accounts;
  }

  public SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return group_id;
    case 1: return accounts;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: group_id = value$ != null ? value$.toString() : null; break;
    case 1: accounts = (java.util.List<Account>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'group_id' field.
   * @return The value of the 'group_id' field.
   */
  public String getGroupId() {
    return group_id;
  }


  /**
   * Sets the value of the 'group_id' field.
   * @param value the value to set.
   */
  public void setGroupId(String value) {
    this.group_id = value;
  }

  /**
   * Gets the value of the 'accounts' field.
   * @return The value of the 'accounts' field.
   */
  public java.util.List<Account> getAccounts() {
    return accounts;
  }


  /**
   * Sets the value of the 'accounts' field.
   * @param value the value to set.
   */
  public void setAccounts(java.util.List<Account> value) {
    this.accounts = value;
  }

  /**
   * Creates a new AccountGroup RecordBuilder.
   * @return A new AccountGroup RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new AccountGroup RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AccountGroup RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new AccountGroup RecordBuilder by copying an existing AccountGroup instance.
   * @param other The existing instance to copy.
   * @return A new AccountGroup RecordBuilder
   */
  public static Builder newBuilder(AccountGroup other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for AccountGroup instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AccountGroup>
    implements org.apache.avro.data.RecordBuilder<AccountGroup> {

    private String group_id;
    private java.util.List<Account> accounts;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.group_id)) {
        this.group_id = data().deepCopy(fields()[0].schema(), other.group_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.accounts)) {
        this.accounts = data().deepCopy(fields()[1].schema(), other.accounts);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing AccountGroup instance
     * @param other The existing instance to copy.
     */
    private Builder(AccountGroup other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.group_id)) {
        this.group_id = data().deepCopy(fields()[0].schema(), other.group_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.accounts)) {
        this.accounts = data().deepCopy(fields()[1].schema(), other.accounts);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'group_id' field.
      * @return The value.
      */
    public String getGroupId() {
      return group_id;
    }


    /**
      * Sets the value of the 'group_id' field.
      * @param value The value of 'group_id'.
      * @return This builder.
      */
    public Builder setGroupId(String value) {
      validate(fields()[0], value);
      this.group_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'group_id' field has been set.
      * @return True if the 'group_id' field has been set, false otherwise.
      */
    public boolean hasGroupId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'group_id' field.
      * @return This builder.
      */
    public Builder clearGroupId() {
      group_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'accounts' field.
      * @return The value.
      */
    public java.util.List<Account> getAccounts() {
      return accounts;
    }


    /**
      * Sets the value of the 'accounts' field.
      * @param value The value of 'accounts'.
      * @return This builder.
      */
    public Builder setAccounts(java.util.List<Account> value) {
      validate(fields()[1], value);
      this.accounts = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'accounts' field has been set.
      * @return True if the 'accounts' field has been set, false otherwise.
      */
    public boolean hasAccounts() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'accounts' field.
      * @return This builder.
      */
    public Builder clearAccounts() {
      accounts = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AccountGroup build() {
      try {
        AccountGroup record = new AccountGroup();
        record.group_id = fieldSetFlags()[0] ? this.group_id : (String) defaultValue(fields()[0]);
        record.accounts = fieldSetFlags()[1] ? this.accounts : (java.util.List<Account>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AccountGroup>
    WRITER$ = (org.apache.avro.io.DatumWriter<AccountGroup>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AccountGroup>
    READER$ = (org.apache.avro.io.DatumReader<AccountGroup>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.group_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.group_id);
    }

    long size0 = this.accounts.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (Account e0: this.accounts) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.group_id = null;
      } else {
        this.group_id = in.readString();
      }

      long size0 = in.readArrayStart();
      java.util.List<Account> a0 = this.accounts;
      if (a0 == null) {
        a0 = new SpecificData.Array<Account>((int)size0, SCHEMA$.getField("accounts").schema());
        this.accounts = a0;
      } else a0.clear();
      SpecificData.Array<Account> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<Account>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          Account e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new Account();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.group_id = null;
          } else {
            this.group_id = in.readString();
          }
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<Account> a0 = this.accounts;
          if (a0 == null) {
            a0 = new SpecificData.Array<Account>((int)size0, SCHEMA$.getField("accounts").schema());
            this.accounts = a0;
          } else a0.clear();
          SpecificData.Array<Account> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<Account>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              Account e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new Account();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










