/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro_pojos;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class Rule extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2247427775611241422L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Rule\",\"namespace\":\"com.sephora.dataplatform.avro\",\"fields\":[{\"name\":\"rule_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"priority\",\"type\":\"int\",\"default\":0},{\"name\":\"rule_value\",\"type\":\"double\",\"default\":0},{\"name\":\"rule_desc\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"rule_action\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"rule_active_flag\",\"type\":\"boolean\",\"default\":false},{\"name\":\"rule_created_date\",\"type\":\"long\",\"default\":0},{\"name\":\"rule_modified_date\",\"type\":\"long\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Rule> ENCODER =
      new BinaryMessageEncoder<Rule>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Rule> DECODER =
      new BinaryMessageDecoder<Rule>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Rule> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Rule> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Rule> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Rule>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Rule to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Rule from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Rule instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Rule fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public String rule_id;
  @Deprecated public int priority;
  @Deprecated public double rule_value;
  @Deprecated public String rule_desc;
  @Deprecated public String rule_action;
  @Deprecated public boolean rule_active_flag;
  @Deprecated public long rule_created_date;
  @Deprecated public long rule_modified_date;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Rule() {}

  /**
   * All-args constructor.
   * @param rule_id The new value for rule_id
   * @param priority The new value for priority
   * @param rule_value The new value for rule_value
   * @param rule_desc The new value for rule_desc
   * @param rule_action The new value for rule_action
   * @param rule_active_flag The new value for rule_active_flag
   * @param rule_created_date The new value for rule_created_date
   * @param rule_modified_date The new value for rule_modified_date
   */
  public Rule(String rule_id, Integer priority, Double rule_value, String rule_desc, String rule_action, Boolean rule_active_flag, Long rule_created_date, Long rule_modified_date) {
    this.rule_id = rule_id;
    this.priority = priority;
    this.rule_value = rule_value;
    this.rule_desc = rule_desc;
    this.rule_action = rule_action;
    this.rule_active_flag = rule_active_flag;
    this.rule_created_date = rule_created_date;
    this.rule_modified_date = rule_modified_date;
  }

  public SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return rule_id;
    case 1: return priority;
    case 2: return rule_value;
    case 3: return rule_desc;
    case 4: return rule_action;
    case 5: return rule_active_flag;
    case 6: return rule_created_date;
    case 7: return rule_modified_date;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: rule_id = value$ != null ? value$.toString() : null; break;
    case 1: priority = (Integer)value$; break;
    case 2: rule_value = (Double)value$; break;
    case 3: rule_desc = value$ != null ? value$.toString() : null; break;
    case 4: rule_action = value$ != null ? value$.toString() : null; break;
    case 5: rule_active_flag = (Boolean)value$; break;
    case 6: rule_created_date = (Long)value$; break;
    case 7: rule_modified_date = (Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'rule_id' field.
   * @return The value of the 'rule_id' field.
   */
  public String getRuleId() {
    return rule_id;
  }


  /**
   * Sets the value of the 'rule_id' field.
   * @param value the value to set.
   */
  public void setRuleId(String value) {
    this.rule_id = value;
  }

  /**
   * Gets the value of the 'priority' field.
   * @return The value of the 'priority' field.
   */
  public int getPriority() {
    return priority;
  }


  /**
   * Sets the value of the 'priority' field.
   * @param value the value to set.
   */
  public void setPriority(int value) {
    this.priority = value;
  }

  /**
   * Gets the value of the 'rule_value' field.
   * @return The value of the 'rule_value' field.
   */
  public double getRuleValue() {
    return rule_value;
  }


  /**
   * Sets the value of the 'rule_value' field.
   * @param value the value to set.
   */
  public void setRuleValue(double value) {
    this.rule_value = value;
  }

  /**
   * Gets the value of the 'rule_desc' field.
   * @return The value of the 'rule_desc' field.
   */
  public String getRuleDesc() {
    return rule_desc;
  }


  /**
   * Sets the value of the 'rule_desc' field.
   * @param value the value to set.
   */
  public void setRuleDesc(String value) {
    this.rule_desc = value;
  }

  /**
   * Gets the value of the 'rule_action' field.
   * @return The value of the 'rule_action' field.
   */
  public String getRuleAction() {
    return rule_action;
  }


  /**
   * Sets the value of the 'rule_action' field.
   * @param value the value to set.
   */
  public void setRuleAction(String value) {
    this.rule_action = value;
  }

  /**
   * Gets the value of the 'rule_active_flag' field.
   * @return The value of the 'rule_active_flag' field.
   */
  public boolean getRuleActiveFlag() {
    return rule_active_flag;
  }


  /**
   * Sets the value of the 'rule_active_flag' field.
   * @param value the value to set.
   */
  public void setRuleActiveFlag(boolean value) {
    this.rule_active_flag = value;
  }

  /**
   * Gets the value of the 'rule_created_date' field.
   * @return The value of the 'rule_created_date' field.
   */
  public long getRuleCreatedDate() {
    return rule_created_date;
  }


  /**
   * Sets the value of the 'rule_created_date' field.
   * @param value the value to set.
   */
  public void setRuleCreatedDate(long value) {
    this.rule_created_date = value;
  }

  /**
   * Gets the value of the 'rule_modified_date' field.
   * @return The value of the 'rule_modified_date' field.
   */
  public long getRuleModifiedDate() {
    return rule_modified_date;
  }


  /**
   * Sets the value of the 'rule_modified_date' field.
   * @param value the value to set.
   */
  public void setRuleModifiedDate(long value) {
    this.rule_modified_date = value;
  }

  /**
   * Creates a new Rule RecordBuilder.
   * @return A new Rule RecordBuilder
   */
  public static Rule.Builder newBuilder() {
    return new Rule.Builder();
  }

  /**
   * Creates a new Rule RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Rule RecordBuilder
   */
  public static Rule.Builder newBuilder(Rule.Builder other) {
    if (other == null) {
      return new Rule.Builder();
    } else {
      return new Rule.Builder(other);
    }
  }

  /**
   * Creates a new Rule RecordBuilder by copying an existing Rule instance.
   * @param other The existing instance to copy.
   * @return A new Rule RecordBuilder
   */
  public static Rule.Builder newBuilder(Rule other) {
    if (other == null) {
      return new Rule.Builder();
    } else {
      return new Rule.Builder(other);
    }
  }

  /**
   * RecordBuilder for Rule instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Rule>
    implements org.apache.avro.data.RecordBuilder<Rule> {

    private String rule_id;
    private int priority;
    private double rule_value;
    private String rule_desc;
    private String rule_action;
    private boolean rule_active_flag;
    private long rule_created_date;
    private long rule_modified_date;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Rule.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.rule_id)) {
        this.rule_id = data().deepCopy(fields()[0].schema(), other.rule_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.priority)) {
        this.priority = data().deepCopy(fields()[1].schema(), other.priority);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.rule_value)) {
        this.rule_value = data().deepCopy(fields()[2].schema(), other.rule_value);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.rule_desc)) {
        this.rule_desc = data().deepCopy(fields()[3].schema(), other.rule_desc);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.rule_action)) {
        this.rule_action = data().deepCopy(fields()[4].schema(), other.rule_action);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.rule_active_flag)) {
        this.rule_active_flag = data().deepCopy(fields()[5].schema(), other.rule_active_flag);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.rule_created_date)) {
        this.rule_created_date = data().deepCopy(fields()[6].schema(), other.rule_created_date);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.rule_modified_date)) {
        this.rule_modified_date = data().deepCopy(fields()[7].schema(), other.rule_modified_date);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing Rule instance
     * @param other The existing instance to copy.
     */
    private Builder(Rule other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.rule_id)) {
        this.rule_id = data().deepCopy(fields()[0].schema(), other.rule_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.priority)) {
        this.priority = data().deepCopy(fields()[1].schema(), other.priority);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.rule_value)) {
        this.rule_value = data().deepCopy(fields()[2].schema(), other.rule_value);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.rule_desc)) {
        this.rule_desc = data().deepCopy(fields()[3].schema(), other.rule_desc);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.rule_action)) {
        this.rule_action = data().deepCopy(fields()[4].schema(), other.rule_action);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.rule_active_flag)) {
        this.rule_active_flag = data().deepCopy(fields()[5].schema(), other.rule_active_flag);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.rule_created_date)) {
        this.rule_created_date = data().deepCopy(fields()[6].schema(), other.rule_created_date);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.rule_modified_date)) {
        this.rule_modified_date = data().deepCopy(fields()[7].schema(), other.rule_modified_date);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'rule_id' field.
      * @return The value.
      */
    public String getRuleId() {
      return rule_id;
    }


    /**
      * Sets the value of the 'rule_id' field.
      * @param value The value of 'rule_id'.
      * @return This builder.
      */
    public Rule.Builder setRuleId(String value) {
      validate(fields()[0], value);
      this.rule_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'rule_id' field has been set.
      * @return True if the 'rule_id' field has been set, false otherwise.
      */
    public boolean hasRuleId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'rule_id' field.
      * @return This builder.
      */
    public Rule.Builder clearRuleId() {
      rule_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'priority' field.
      * @return The value.
      */
    public int getPriority() {
      return priority;
    }


    /**
      * Sets the value of the 'priority' field.
      * @param value The value of 'priority'.
      * @return This builder.
      */
    public Rule.Builder setPriority(int value) {
      validate(fields()[1], value);
      this.priority = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'priority' field has been set.
      * @return True if the 'priority' field has been set, false otherwise.
      */
    public boolean hasPriority() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'priority' field.
      * @return This builder.
      */
    public Rule.Builder clearPriority() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'rule_value' field.
      * @return The value.
      */
    public double getRuleValue() {
      return rule_value;
    }


    /**
      * Sets the value of the 'rule_value' field.
      * @param value The value of 'rule_value'.
      * @return This builder.
      */
    public Rule.Builder setRuleValue(double value) {
      validate(fields()[2], value);
      this.rule_value = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'rule_value' field has been set.
      * @return True if the 'rule_value' field has been set, false otherwise.
      */
    public boolean hasRuleValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'rule_value' field.
      * @return This builder.
      */
    public Rule.Builder clearRuleValue() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'rule_desc' field.
      * @return The value.
      */
    public String getRuleDesc() {
      return rule_desc;
    }


    /**
      * Sets the value of the 'rule_desc' field.
      * @param value The value of 'rule_desc'.
      * @return This builder.
      */
    public Rule.Builder setRuleDesc(String value) {
      validate(fields()[3], value);
      this.rule_desc = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'rule_desc' field has been set.
      * @return True if the 'rule_desc' field has been set, false otherwise.
      */
    public boolean hasRuleDesc() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'rule_desc' field.
      * @return This builder.
      */
    public Rule.Builder clearRuleDesc() {
      rule_desc = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'rule_action' field.
      * @return The value.
      */
    public String getRuleAction() {
      return rule_action;
    }


    /**
      * Sets the value of the 'rule_action' field.
      * @param value The value of 'rule_action'.
      * @return This builder.
      */
    public Rule.Builder setRuleAction(String value) {
      validate(fields()[4], value);
      this.rule_action = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'rule_action' field has been set.
      * @return True if the 'rule_action' field has been set, false otherwise.
      */
    public boolean hasRuleAction() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'rule_action' field.
      * @return This builder.
      */
    public Rule.Builder clearRuleAction() {
      rule_action = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'rule_active_flag' field.
      * @return The value.
      */
    public boolean getRuleActiveFlag() {
      return rule_active_flag;
    }


    /**
      * Sets the value of the 'rule_active_flag' field.
      * @param value The value of 'rule_active_flag'.
      * @return This builder.
      */
    public Rule.Builder setRuleActiveFlag(boolean value) {
      validate(fields()[5], value);
      this.rule_active_flag = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'rule_active_flag' field has been set.
      * @return True if the 'rule_active_flag' field has been set, false otherwise.
      */
    public boolean hasRuleActiveFlag() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'rule_active_flag' field.
      * @return This builder.
      */
    public Rule.Builder clearRuleActiveFlag() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'rule_created_date' field.
      * @return The value.
      */
    public long getRuleCreatedDate() {
      return rule_created_date;
    }


    /**
      * Sets the value of the 'rule_created_date' field.
      * @param value The value of 'rule_created_date'.
      * @return This builder.
      */
    public Rule.Builder setRuleCreatedDate(long value) {
      validate(fields()[6], value);
      this.rule_created_date = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'rule_created_date' field has been set.
      * @return True if the 'rule_created_date' field has been set, false otherwise.
      */
    public boolean hasRuleCreatedDate() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'rule_created_date' field.
      * @return This builder.
      */
    public Rule.Builder clearRuleCreatedDate() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'rule_modified_date' field.
      * @return The value.
      */
    public long getRuleModifiedDate() {
      return rule_modified_date;
    }


    /**
      * Sets the value of the 'rule_modified_date' field.
      * @param value The value of 'rule_modified_date'.
      * @return This builder.
      */
    public Rule.Builder setRuleModifiedDate(long value) {
      validate(fields()[7], value);
      this.rule_modified_date = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'rule_modified_date' field has been set.
      * @return True if the 'rule_modified_date' field has been set, false otherwise.
      */
    public boolean hasRuleModifiedDate() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'rule_modified_date' field.
      * @return This builder.
      */
    public Rule.Builder clearRuleModifiedDate() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Rule build() {
      try {
        Rule record = new Rule();
        record.rule_id = fieldSetFlags()[0] ? this.rule_id : (String) defaultValue(fields()[0]);
        record.priority = fieldSetFlags()[1] ? this.priority : (Integer) defaultValue(fields()[1]);
        record.rule_value = fieldSetFlags()[2] ? this.rule_value : (Double) defaultValue(fields()[2]);
        record.rule_desc = fieldSetFlags()[3] ? this.rule_desc : (String) defaultValue(fields()[3]);
        record.rule_action = fieldSetFlags()[4] ? this.rule_action : (String) defaultValue(fields()[4]);
        record.rule_active_flag = fieldSetFlags()[5] ? this.rule_active_flag : (Boolean) defaultValue(fields()[5]);
        record.rule_created_date = fieldSetFlags()[6] ? this.rule_created_date : (Long) defaultValue(fields()[6]);
        record.rule_modified_date = fieldSetFlags()[7] ? this.rule_modified_date : (Long) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Rule>
    WRITER$ = (org.apache.avro.io.DatumWriter<Rule>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Rule>
    READER$ = (org.apache.avro.io.DatumReader<Rule>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.rule_id);

    out.writeInt(this.priority);

    out.writeDouble(this.rule_value);

    out.writeString(this.rule_desc);

    out.writeString(this.rule_action);

    out.writeBoolean(this.rule_active_flag);

    out.writeLong(this.rule_created_date);

    out.writeLong(this.rule_modified_date);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.rule_id = in.readString();

      this.priority = in.readInt();

      this.rule_value = in.readDouble();

      this.rule_desc = in.readString();

      this.rule_action = in.readString();

      this.rule_active_flag = in.readBoolean();

      this.rule_created_date = in.readLong();

      this.rule_modified_date = in.readLong();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.rule_id = in.readString();
          break;

        case 1:
          this.priority = in.readInt();
          break;

        case 2:
          this.rule_value = in.readDouble();
          break;

        case 3:
          this.rule_desc = in.readString();
          break;

        case 4:
          this.rule_action = in.readString();
          break;

        case 5:
          this.rule_active_flag = in.readBoolean();
          break;

        case 6:
          this.rule_created_date = in.readLong();
          break;

        case 7:
          this.rule_modified_date = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










