/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro_pojos;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class USR_ASN_AUDIT_LOG extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8399464952200738412L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"USR_ASN_AUDIT_LOG\",\"namespace\":\"com.sephora.scm.wms.data\",\"fields\":[{\"name\":\"meta_tbnm\",\"type\":\"string\"},{\"name\":\"meta_chgtyp\",\"type\":\"string\"},{\"name\":\"meta_chgtm\",\"type\":\"string\"},{\"name\":\"audit_log_id\",\"type\":\"string\"},{\"name\":\"wh_id\",\"type\":\"string\"},{\"name\":\"trndte\",\"type\":[\"string\",\"null\"]},{\"name\":\"asnaudtyp\",\"type\":\"string\"},{\"name\":\"invnum\",\"type\":[\"string\",\"null\"]},{\"name\":\"supnum\",\"type\":[\"string\",\"null\"]},{\"name\":\"client_id\",\"type\":[\"string\",\"null\"]},{\"name\":\"trknum\",\"type\":[\"string\",\"null\"]},{\"name\":\"dept_cod\",\"type\":[\"string\",\"null\"]},{\"name\":\"uc_brand\",\"type\":[\"string\",\"null\"]},{\"name\":\"subnum\",\"type\":[\"string\",\"null\"]},{\"name\":\"dstsub\",\"type\":[\"string\",\"null\"]},{\"name\":\"aud_prtnum\",\"type\":[\"string\",\"null\"]},{\"name\":\"aud_prt_client_id\",\"type\":[\"string\",\"null\"]},{\"name\":\"audqty\",\"type\":[\"int\",\"null\"]},{\"name\":\"asn_prtnum\",\"type\":[\"string\",\"null\"]},{\"name\":\"asn_prt_client_id\",\"type\":[\"string\",\"null\"]},{\"name\":\"asnqty\",\"type\":[\"int\",\"null\"]},{\"name\":\"multi_sku_flg\",\"type\":\"int\"},{\"name\":\"asn_upd_flg\",\"type\":\"int\"},{\"name\":\"appt_id\",\"type\":[\"string\",\"null\"]},{\"name\":\"asntotcnt\",\"type\":[\"int\",\"null\"]},{\"name\":\"asnaudcnt\",\"type\":[\"int\",\"null\"]},{\"name\":\"asnrvscnt\",\"type\":[\"int\",\"null\"]},{\"name\":\"asnflgcnt\",\"type\":[\"int\",\"null\"]},{\"name\":\"audthrhbrkflg\",\"type\":\"int\"},{\"name\":\"audremcnt\",\"type\":[\"int\",\"null\"]},{\"name\":\"audit_usr_id\",\"type\":[\"string\",\"null\"]},{\"name\":\"aud_upc\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<USR_ASN_AUDIT_LOG> ENCODER =
      new BinaryMessageEncoder<USR_ASN_AUDIT_LOG>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<USR_ASN_AUDIT_LOG> DECODER =
      new BinaryMessageDecoder<USR_ASN_AUDIT_LOG>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<USR_ASN_AUDIT_LOG> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<USR_ASN_AUDIT_LOG> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<USR_ASN_AUDIT_LOG>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this USR_ASN_AUDIT_LOG to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a USR_ASN_AUDIT_LOG from a ByteBuffer. */
  public static USR_ASN_AUDIT_LOG fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public CharSequence meta_tbnm;
  @Deprecated public CharSequence meta_chgtyp;
  @Deprecated public CharSequence meta_chgtm;
  @Deprecated public CharSequence audit_log_id;
  @Deprecated public CharSequence wh_id;
  @Deprecated public CharSequence trndte;
  @Deprecated public CharSequence asnaudtyp;
  @Deprecated public CharSequence invnum;
  @Deprecated public CharSequence supnum;
  @Deprecated public CharSequence client_id;
  @Deprecated public CharSequence trknum;
  @Deprecated public CharSequence dept_cod;
  @Deprecated public CharSequence uc_brand;
  @Deprecated public CharSequence subnum;
  @Deprecated public CharSequence dstsub;
  @Deprecated public CharSequence aud_prtnum;
  @Deprecated public CharSequence aud_prt_client_id;
  @Deprecated public Integer audqty;
  @Deprecated public CharSequence asn_prtnum;
  @Deprecated public CharSequence asn_prt_client_id;
  @Deprecated public Integer asnqty;
  @Deprecated public int multi_sku_flg;
  @Deprecated public int asn_upd_flg;
  @Deprecated public CharSequence appt_id;
  @Deprecated public Integer asntotcnt;
  @Deprecated public Integer asnaudcnt;
  @Deprecated public Integer asnrvscnt;
  @Deprecated public Integer asnflgcnt;
  @Deprecated public int audthrhbrkflg;
  @Deprecated public Integer audremcnt;
  @Deprecated public CharSequence audit_usr_id;
  @Deprecated public CharSequence aud_upc;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public USR_ASN_AUDIT_LOG() {}

  /**
   * All-args constructor.
   * @param meta_tbnm The new value for meta_tbnm
   * @param meta_chgtyp The new value for meta_chgtyp
   * @param meta_chgtm The new value for meta_chgtm
   * @param audit_log_id The new value for audit_log_id
   * @param wh_id The new value for wh_id
   * @param trndte The new value for trndte
   * @param asnaudtyp The new value for asnaudtyp
   * @param invnum The new value for invnum
   * @param supnum The new value for supnum
   * @param client_id The new value for client_id
   * @param trknum The new value for trknum
   * @param dept_cod The new value for dept_cod
   * @param uc_brand The new value for uc_brand
   * @param subnum The new value for subnum
   * @param dstsub The new value for dstsub
   * @param aud_prtnum The new value for aud_prtnum
   * @param aud_prt_client_id The new value for aud_prt_client_id
   * @param audqty The new value for audqty
   * @param asn_prtnum The new value for asn_prtnum
   * @param asn_prt_client_id The new value for asn_prt_client_id
   * @param asnqty The new value for asnqty
   * @param multi_sku_flg The new value for multi_sku_flg
   * @param asn_upd_flg The new value for asn_upd_flg
   * @param appt_id The new value for appt_id
   * @param asntotcnt The new value for asntotcnt
   * @param asnaudcnt The new value for asnaudcnt
   * @param asnrvscnt The new value for asnrvscnt
   * @param asnflgcnt The new value for asnflgcnt
   * @param audthrhbrkflg The new value for audthrhbrkflg
   * @param audremcnt The new value for audremcnt
   * @param audit_usr_id The new value for audit_usr_id
   * @param aud_upc The new value for aud_upc
   */
  public USR_ASN_AUDIT_LOG(CharSequence meta_tbnm, CharSequence meta_chgtyp, CharSequence meta_chgtm, CharSequence audit_log_id, CharSequence wh_id, CharSequence trndte, CharSequence asnaudtyp, CharSequence invnum, CharSequence supnum, CharSequence client_id, CharSequence trknum, CharSequence dept_cod, CharSequence uc_brand, CharSequence subnum, CharSequence dstsub, CharSequence aud_prtnum, CharSequence aud_prt_client_id, Integer audqty, CharSequence asn_prtnum, CharSequence asn_prt_client_id, Integer asnqty, Integer multi_sku_flg, Integer asn_upd_flg, CharSequence appt_id, Integer asntotcnt, Integer asnaudcnt, Integer asnrvscnt, Integer asnflgcnt, Integer audthrhbrkflg, Integer audremcnt, CharSequence audit_usr_id, CharSequence aud_upc) {
    this.meta_tbnm = meta_tbnm;
    this.meta_chgtyp = meta_chgtyp;
    this.meta_chgtm = meta_chgtm;
    this.audit_log_id = audit_log_id;
    this.wh_id = wh_id;
    this.trndte = trndte;
    this.asnaudtyp = asnaudtyp;
    this.invnum = invnum;
    this.supnum = supnum;
    this.client_id = client_id;
    this.trknum = trknum;
    this.dept_cod = dept_cod;
    this.uc_brand = uc_brand;
    this.subnum = subnum;
    this.dstsub = dstsub;
    this.aud_prtnum = aud_prtnum;
    this.aud_prt_client_id = aud_prt_client_id;
    this.audqty = audqty;
    this.asn_prtnum = asn_prtnum;
    this.asn_prt_client_id = asn_prt_client_id;
    this.asnqty = asnqty;
    this.multi_sku_flg = multi_sku_flg;
    this.asn_upd_flg = asn_upd_flg;
    this.appt_id = appt_id;
    this.asntotcnt = asntotcnt;
    this.asnaudcnt = asnaudcnt;
    this.asnrvscnt = asnrvscnt;
    this.asnflgcnt = asnflgcnt;
    this.audthrhbrkflg = audthrhbrkflg;
    this.audremcnt = audremcnt;
    this.audit_usr_id = audit_usr_id;
    this.aud_upc = aud_upc;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return meta_tbnm;
    case 1: return meta_chgtyp;
    case 2: return meta_chgtm;
    case 3: return audit_log_id;
    case 4: return wh_id;
    case 5: return trndte;
    case 6: return asnaudtyp;
    case 7: return invnum;
    case 8: return supnum;
    case 9: return client_id;
    case 10: return trknum;
    case 11: return dept_cod;
    case 12: return uc_brand;
    case 13: return subnum;
    case 14: return dstsub;
    case 15: return aud_prtnum;
    case 16: return aud_prt_client_id;
    case 17: return audqty;
    case 18: return asn_prtnum;
    case 19: return asn_prt_client_id;
    case 20: return asnqty;
    case 21: return multi_sku_flg;
    case 22: return asn_upd_flg;
    case 23: return appt_id;
    case 24: return asntotcnt;
    case 25: return asnaudcnt;
    case 26: return asnrvscnt;
    case 27: return asnflgcnt;
    case 28: return audthrhbrkflg;
    case 29: return audremcnt;
    case 30: return audit_usr_id;
    case 31: return aud_upc;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: meta_tbnm = (CharSequence)value$; break;
    case 1: meta_chgtyp = (CharSequence)value$; break;
    case 2: meta_chgtm = (CharSequence)value$; break;
    case 3: audit_log_id = (CharSequence)value$; break;
    case 4: wh_id = (CharSequence)value$; break;
    case 5: trndte = (CharSequence)value$; break;
    case 6: asnaudtyp = (CharSequence)value$; break;
    case 7: invnum = (CharSequence)value$; break;
    case 8: supnum = (CharSequence)value$; break;
    case 9: client_id = (CharSequence)value$; break;
    case 10: trknum = (CharSequence)value$; break;
    case 11: dept_cod = (CharSequence)value$; break;
    case 12: uc_brand = (CharSequence)value$; break;
    case 13: subnum = (CharSequence)value$; break;
    case 14: dstsub = (CharSequence)value$; break;
    case 15: aud_prtnum = (CharSequence)value$; break;
    case 16: aud_prt_client_id = (CharSequence)value$; break;
    case 17: audqty = (Integer)value$; break;
    case 18: asn_prtnum = (CharSequence)value$; break;
    case 19: asn_prt_client_id = (CharSequence)value$; break;
    case 20: asnqty = (Integer)value$; break;
    case 21: multi_sku_flg = (Integer)value$; break;
    case 22: asn_upd_flg = (Integer)value$; break;
    case 23: appt_id = (CharSequence)value$; break;
    case 24: asntotcnt = (Integer)value$; break;
    case 25: asnaudcnt = (Integer)value$; break;
    case 26: asnrvscnt = (Integer)value$; break;
    case 27: asnflgcnt = (Integer)value$; break;
    case 28: audthrhbrkflg = (Integer)value$; break;
    case 29: audremcnt = (Integer)value$; break;
    case 30: audit_usr_id = (CharSequence)value$; break;
    case 31: aud_upc = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'meta_tbnm' field.
   * @return The value of the 'meta_tbnm' field.
   */
  public CharSequence getMetaTbnm() {
    return meta_tbnm;
  }

  /**
   * Sets the value of the 'meta_tbnm' field.
   * @param value the value to set.
   */
  public void setMetaTbnm(CharSequence value) {
    this.meta_tbnm = value;
  }

  /**
   * Gets the value of the 'meta_chgtyp' field.
   * @return The value of the 'meta_chgtyp' field.
   */
  public CharSequence getMetaChgtyp() {
    return meta_chgtyp;
  }

  /**
   * Sets the value of the 'meta_chgtyp' field.
   * @param value the value to set.
   */
  public void setMetaChgtyp(CharSequence value) {
    this.meta_chgtyp = value;
  }

  /**
   * Gets the value of the 'meta_chgtm' field.
   * @return The value of the 'meta_chgtm' field.
   */
  public CharSequence getMetaChgtm() {
    return meta_chgtm;
  }

  /**
   * Sets the value of the 'meta_chgtm' field.
   * @param value the value to set.
   */
  public void setMetaChgtm(CharSequence value) {
    this.meta_chgtm = value;
  }

  /**
   * Gets the value of the 'audit_log_id' field.
   * @return The value of the 'audit_log_id' field.
   */
  public CharSequence getAuditLogId() {
    return audit_log_id;
  }

  /**
   * Sets the value of the 'audit_log_id' field.
   * @param value the value to set.
   */
  public void setAuditLogId(CharSequence value) {
    this.audit_log_id = value;
  }

  /**
   * Gets the value of the 'wh_id' field.
   * @return The value of the 'wh_id' field.
   */
  public CharSequence getWhId() {
    return wh_id;
  }

  /**
   * Sets the value of the 'wh_id' field.
   * @param value the value to set.
   */
  public void setWhId(CharSequence value) {
    this.wh_id = value;
  }

  /**
   * Gets the value of the 'trndte' field.
   * @return The value of the 'trndte' field.
   */
  public CharSequence getTrndte() {
    return trndte;
  }

  /**
   * Sets the value of the 'trndte' field.
   * @param value the value to set.
   */
  public void setTrndte(CharSequence value) {
    this.trndte = value;
  }

  /**
   * Gets the value of the 'asnaudtyp' field.
   * @return The value of the 'asnaudtyp' field.
   */
  public CharSequence getAsnaudtyp() {
    return asnaudtyp;
  }

  /**
   * Sets the value of the 'asnaudtyp' field.
   * @param value the value to set.
   */
  public void setAsnaudtyp(CharSequence value) {
    this.asnaudtyp = value;
  }

  /**
   * Gets the value of the 'invnum' field.
   * @return The value of the 'invnum' field.
   */
  public CharSequence getInvnum() {
    return invnum;
  }

  /**
   * Sets the value of the 'invnum' field.
   * @param value the value to set.
   */
  public void setInvnum(CharSequence value) {
    this.invnum = value;
  }

  /**
   * Gets the value of the 'supnum' field.
   * @return The value of the 'supnum' field.
   */
  public CharSequence getSupnum() {
    return supnum;
  }

  /**
   * Sets the value of the 'supnum' field.
   * @param value the value to set.
   */
  public void setSupnum(CharSequence value) {
    this.supnum = value;
  }

  /**
   * Gets the value of the 'client_id' field.
   * @return The value of the 'client_id' field.
   */
  public CharSequence getClientId() {
    return client_id;
  }

  /**
   * Sets the value of the 'client_id' field.
   * @param value the value to set.
   */
  public void setClientId(CharSequence value) {
    this.client_id = value;
  }

  /**
   * Gets the value of the 'trknum' field.
   * @return The value of the 'trknum' field.
   */
  public CharSequence getTrknum() {
    return trknum;
  }

  /**
   * Sets the value of the 'trknum' field.
   * @param value the value to set.
   */
  public void setTrknum(CharSequence value) {
    this.trknum = value;
  }

  /**
   * Gets the value of the 'dept_cod' field.
   * @return The value of the 'dept_cod' field.
   */
  public CharSequence getDeptCod() {
    return dept_cod;
  }

  /**
   * Sets the value of the 'dept_cod' field.
   * @param value the value to set.
   */
  public void setDeptCod(CharSequence value) {
    this.dept_cod = value;
  }

  /**
   * Gets the value of the 'uc_brand' field.
   * @return The value of the 'uc_brand' field.
   */
  public CharSequence getUcBrand() {
    return uc_brand;
  }

  /**
   * Sets the value of the 'uc_brand' field.
   * @param value the value to set.
   */
  public void setUcBrand(CharSequence value) {
    this.uc_brand = value;
  }

  /**
   * Gets the value of the 'subnum' field.
   * @return The value of the 'subnum' field.
   */
  public CharSequence getSubnum() {
    return subnum;
  }

  /**
   * Sets the value of the 'subnum' field.
   * @param value the value to set.
   */
  public void setSubnum(CharSequence value) {
    this.subnum = value;
  }

  /**
   * Gets the value of the 'dstsub' field.
   * @return The value of the 'dstsub' field.
   */
  public CharSequence getDstsub() {
    return dstsub;
  }

  /**
   * Sets the value of the 'dstsub' field.
   * @param value the value to set.
   */
  public void setDstsub(CharSequence value) {
    this.dstsub = value;
  }

  /**
   * Gets the value of the 'aud_prtnum' field.
   * @return The value of the 'aud_prtnum' field.
   */
  public CharSequence getAudPrtnum() {
    return aud_prtnum;
  }

  /**
   * Sets the value of the 'aud_prtnum' field.
   * @param value the value to set.
   */
  public void setAudPrtnum(CharSequence value) {
    this.aud_prtnum = value;
  }

  /**
   * Gets the value of the 'aud_prt_client_id' field.
   * @return The value of the 'aud_prt_client_id' field.
   */
  public CharSequence getAudPrtClientId() {
    return aud_prt_client_id;
  }

  /**
   * Sets the value of the 'aud_prt_client_id' field.
   * @param value the value to set.
   */
  public void setAudPrtClientId(CharSequence value) {
    this.aud_prt_client_id = value;
  }

  /**
   * Gets the value of the 'audqty' field.
   * @return The value of the 'audqty' field.
   */
  public Integer getAudqty() {
    return audqty;
  }

  /**
   * Sets the value of the 'audqty' field.
   * @param value the value to set.
   */
  public void setAudqty(Integer value) {
    this.audqty = value;
  }

  /**
   * Gets the value of the 'asn_prtnum' field.
   * @return The value of the 'asn_prtnum' field.
   */
  public CharSequence getAsnPrtnum() {
    return asn_prtnum;
  }

  /**
   * Sets the value of the 'asn_prtnum' field.
   * @param value the value to set.
   */
  public void setAsnPrtnum(CharSequence value) {
    this.asn_prtnum = value;
  }

  /**
   * Gets the value of the 'asn_prt_client_id' field.
   * @return The value of the 'asn_prt_client_id' field.
   */
  public CharSequence getAsnPrtClientId() {
    return asn_prt_client_id;
  }

  /**
   * Sets the value of the 'asn_prt_client_id' field.
   * @param value the value to set.
   */
  public void setAsnPrtClientId(CharSequence value) {
    this.asn_prt_client_id = value;
  }

  /**
   * Gets the value of the 'asnqty' field.
   * @return The value of the 'asnqty' field.
   */
  public Integer getAsnqty() {
    return asnqty;
  }

  /**
   * Sets the value of the 'asnqty' field.
   * @param value the value to set.
   */
  public void setAsnqty(Integer value) {
    this.asnqty = value;
  }

  /**
   * Gets the value of the 'multi_sku_flg' field.
   * @return The value of the 'multi_sku_flg' field.
   */
  public Integer getMultiSkuFlg() {
    return multi_sku_flg;
  }

  /**
   * Sets the value of the 'multi_sku_flg' field.
   * @param value the value to set.
   */
  public void setMultiSkuFlg(Integer value) {
    this.multi_sku_flg = value;
  }

  /**
   * Gets the value of the 'asn_upd_flg' field.
   * @return The value of the 'asn_upd_flg' field.
   */
  public Integer getAsnUpdFlg() {
    return asn_upd_flg;
  }

  /**
   * Sets the value of the 'asn_upd_flg' field.
   * @param value the value to set.
   */
  public void setAsnUpdFlg(Integer value) {
    this.asn_upd_flg = value;
  }

  /**
   * Gets the value of the 'appt_id' field.
   * @return The value of the 'appt_id' field.
   */
  public CharSequence getApptId() {
    return appt_id;
  }

  /**
   * Sets the value of the 'appt_id' field.
   * @param value the value to set.
   */
  public void setApptId(CharSequence value) {
    this.appt_id = value;
  }

  /**
   * Gets the value of the 'asntotcnt' field.
   * @return The value of the 'asntotcnt' field.
   */
  public Integer getAsntotcnt() {
    return asntotcnt;
  }

  /**
   * Sets the value of the 'asntotcnt' field.
   * @param value the value to set.
   */
  public void setAsntotcnt(Integer value) {
    this.asntotcnt = value;
  }

  /**
   * Gets the value of the 'asnaudcnt' field.
   * @return The value of the 'asnaudcnt' field.
   */
  public Integer getAsnaudcnt() {
    return asnaudcnt;
  }

  /**
   * Sets the value of the 'asnaudcnt' field.
   * @param value the value to set.
   */
  public void setAsnaudcnt(Integer value) {
    this.asnaudcnt = value;
  }

  /**
   * Gets the value of the 'asnrvscnt' field.
   * @return The value of the 'asnrvscnt' field.
   */
  public Integer getAsnrvscnt() {
    return asnrvscnt;
  }

  /**
   * Sets the value of the 'asnrvscnt' field.
   * @param value the value to set.
   */
  public void setAsnrvscnt(Integer value) {
    this.asnrvscnt = value;
  }

  /**
   * Gets the value of the 'asnflgcnt' field.
   * @return The value of the 'asnflgcnt' field.
   */
  public Integer getAsnflgcnt() {
    return asnflgcnt;
  }

  /**
   * Sets the value of the 'asnflgcnt' field.
   * @param value the value to set.
   */
  public void setAsnflgcnt(Integer value) {
    this.asnflgcnt = value;
  }

  /**
   * Gets the value of the 'audthrhbrkflg' field.
   * @return The value of the 'audthrhbrkflg' field.
   */
  public Integer getAudthrhbrkflg() {
    return audthrhbrkflg;
  }

  /**
   * Sets the value of the 'audthrhbrkflg' field.
   * @param value the value to set.
   */
  public void setAudthrhbrkflg(Integer value) {
    this.audthrhbrkflg = value;
  }

  /**
   * Gets the value of the 'audremcnt' field.
   * @return The value of the 'audremcnt' field.
   */
  public Integer getAudremcnt() {
    return audremcnt;
  }

  /**
   * Sets the value of the 'audremcnt' field.
   * @param value the value to set.
   */
  public void setAudremcnt(Integer value) {
    this.audremcnt = value;
  }

  /**
   * Gets the value of the 'audit_usr_id' field.
   * @return The value of the 'audit_usr_id' field.
   */
  public CharSequence getAuditUsrId() {
    return audit_usr_id;
  }

  /**
   * Sets the value of the 'audit_usr_id' field.
   * @param value the value to set.
   */
  public void setAuditUsrId(CharSequence value) {
    this.audit_usr_id = value;
  }

  /**
   * Gets the value of the 'aud_upc' field.
   * @return The value of the 'aud_upc' field.
   */
  public CharSequence getAudUpc() {
    return aud_upc;
  }

  /**
   * Sets the value of the 'aud_upc' field.
   * @param value the value to set.
   */
  public void setAudUpc(CharSequence value) {
    this.aud_upc = value;
  }

  /**
   * Creates a new USR_ASN_AUDIT_LOG RecordBuilder.
   * @return A new USR_ASN_AUDIT_LOG RecordBuilder
   */
  public static USR_ASN_AUDIT_LOG.Builder newBuilder() {
    return new USR_ASN_AUDIT_LOG.Builder();
  }

  /**
   * Creates a new USR_ASN_AUDIT_LOG RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new USR_ASN_AUDIT_LOG RecordBuilder
   */
  public static USR_ASN_AUDIT_LOG.Builder newBuilder(USR_ASN_AUDIT_LOG.Builder other) {
    return new USR_ASN_AUDIT_LOG.Builder(other);
  }

  /**
   * Creates a new USR_ASN_AUDIT_LOG RecordBuilder by copying an existing USR_ASN_AUDIT_LOG instance.
   * @param other The existing instance to copy.
   * @return A new USR_ASN_AUDIT_LOG RecordBuilder
   */
  public static USR_ASN_AUDIT_LOG.Builder newBuilder(USR_ASN_AUDIT_LOG other) {
    return new USR_ASN_AUDIT_LOG.Builder(other);
  }

  /**
   * RecordBuilder for USR_ASN_AUDIT_LOG instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<USR_ASN_AUDIT_LOG>
    implements org.apache.avro.data.RecordBuilder<USR_ASN_AUDIT_LOG> {

    private CharSequence meta_tbnm;
    private CharSequence meta_chgtyp;
    private CharSequence meta_chgtm;
    private CharSequence audit_log_id;
    private CharSequence wh_id;
    private CharSequence trndte;
    private CharSequence asnaudtyp;
    private CharSequence invnum;
    private CharSequence supnum;
    private CharSequence client_id;
    private CharSequence trknum;
    private CharSequence dept_cod;
    private CharSequence uc_brand;
    private CharSequence subnum;
    private CharSequence dstsub;
    private CharSequence aud_prtnum;
    private CharSequence aud_prt_client_id;
    private Integer audqty;
    private CharSequence asn_prtnum;
    private CharSequence asn_prt_client_id;
    private Integer asnqty;
    private int multi_sku_flg;
    private int asn_upd_flg;
    private CharSequence appt_id;
    private Integer asntotcnt;
    private Integer asnaudcnt;
    private Integer asnrvscnt;
    private Integer asnflgcnt;
    private int audthrhbrkflg;
    private Integer audremcnt;
    private CharSequence audit_usr_id;
    private CharSequence aud_upc;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(USR_ASN_AUDIT_LOG.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.meta_tbnm)) {
        this.meta_tbnm = data().deepCopy(fields()[0].schema(), other.meta_tbnm);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.meta_chgtyp)) {
        this.meta_chgtyp = data().deepCopy(fields()[1].schema(), other.meta_chgtyp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.meta_chgtm)) {
        this.meta_chgtm = data().deepCopy(fields()[2].schema(), other.meta_chgtm);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.audit_log_id)) {
        this.audit_log_id = data().deepCopy(fields()[3].schema(), other.audit_log_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.wh_id)) {
        this.wh_id = data().deepCopy(fields()[4].schema(), other.wh_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.trndte)) {
        this.trndte = data().deepCopy(fields()[5].schema(), other.trndte);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.asnaudtyp)) {
        this.asnaudtyp = data().deepCopy(fields()[6].schema(), other.asnaudtyp);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.invnum)) {
        this.invnum = data().deepCopy(fields()[7].schema(), other.invnum);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.supnum)) {
        this.supnum = data().deepCopy(fields()[8].schema(), other.supnum);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.client_id)) {
        this.client_id = data().deepCopy(fields()[9].schema(), other.client_id);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.trknum)) {
        this.trknum = data().deepCopy(fields()[10].schema(), other.trknum);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.dept_cod)) {
        this.dept_cod = data().deepCopy(fields()[11].schema(), other.dept_cod);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.uc_brand)) {
        this.uc_brand = data().deepCopy(fields()[12].schema(), other.uc_brand);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.subnum)) {
        this.subnum = data().deepCopy(fields()[13].schema(), other.subnum);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.dstsub)) {
        this.dstsub = data().deepCopy(fields()[14].schema(), other.dstsub);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.aud_prtnum)) {
        this.aud_prtnum = data().deepCopy(fields()[15].schema(), other.aud_prtnum);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.aud_prt_client_id)) {
        this.aud_prt_client_id = data().deepCopy(fields()[16].schema(), other.aud_prt_client_id);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.audqty)) {
        this.audqty = data().deepCopy(fields()[17].schema(), other.audqty);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.asn_prtnum)) {
        this.asn_prtnum = data().deepCopy(fields()[18].schema(), other.asn_prtnum);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.asn_prt_client_id)) {
        this.asn_prt_client_id = data().deepCopy(fields()[19].schema(), other.asn_prt_client_id);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.asnqty)) {
        this.asnqty = data().deepCopy(fields()[20].schema(), other.asnqty);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.multi_sku_flg)) {
        this.multi_sku_flg = data().deepCopy(fields()[21].schema(), other.multi_sku_flg);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.asn_upd_flg)) {
        this.asn_upd_flg = data().deepCopy(fields()[22].schema(), other.asn_upd_flg);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.appt_id)) {
        this.appt_id = data().deepCopy(fields()[23].schema(), other.appt_id);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.asntotcnt)) {
        this.asntotcnt = data().deepCopy(fields()[24].schema(), other.asntotcnt);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.asnaudcnt)) {
        this.asnaudcnt = data().deepCopy(fields()[25].schema(), other.asnaudcnt);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.asnrvscnt)) {
        this.asnrvscnt = data().deepCopy(fields()[26].schema(), other.asnrvscnt);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.asnflgcnt)) {
        this.asnflgcnt = data().deepCopy(fields()[27].schema(), other.asnflgcnt);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.audthrhbrkflg)) {
        this.audthrhbrkflg = data().deepCopy(fields()[28].schema(), other.audthrhbrkflg);
        fieldSetFlags()[28] = true;
      }
      if (isValidValue(fields()[29], other.audremcnt)) {
        this.audremcnt = data().deepCopy(fields()[29].schema(), other.audremcnt);
        fieldSetFlags()[29] = true;
      }
      if (isValidValue(fields()[30], other.audit_usr_id)) {
        this.audit_usr_id = data().deepCopy(fields()[30].schema(), other.audit_usr_id);
        fieldSetFlags()[30] = true;
      }
      if (isValidValue(fields()[31], other.aud_upc)) {
        this.aud_upc = data().deepCopy(fields()[31].schema(), other.aud_upc);
        fieldSetFlags()[31] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing USR_ASN_AUDIT_LOG instance
     * @param other The existing instance to copy.
     */
    private Builder(USR_ASN_AUDIT_LOG other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.meta_tbnm)) {
        this.meta_tbnm = data().deepCopy(fields()[0].schema(), other.meta_tbnm);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.meta_chgtyp)) {
        this.meta_chgtyp = data().deepCopy(fields()[1].schema(), other.meta_chgtyp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.meta_chgtm)) {
        this.meta_chgtm = data().deepCopy(fields()[2].schema(), other.meta_chgtm);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.audit_log_id)) {
        this.audit_log_id = data().deepCopy(fields()[3].schema(), other.audit_log_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.wh_id)) {
        this.wh_id = data().deepCopy(fields()[4].schema(), other.wh_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.trndte)) {
        this.trndte = data().deepCopy(fields()[5].schema(), other.trndte);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.asnaudtyp)) {
        this.asnaudtyp = data().deepCopy(fields()[6].schema(), other.asnaudtyp);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.invnum)) {
        this.invnum = data().deepCopy(fields()[7].schema(), other.invnum);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.supnum)) {
        this.supnum = data().deepCopy(fields()[8].schema(), other.supnum);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.client_id)) {
        this.client_id = data().deepCopy(fields()[9].schema(), other.client_id);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.trknum)) {
        this.trknum = data().deepCopy(fields()[10].schema(), other.trknum);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.dept_cod)) {
        this.dept_cod = data().deepCopy(fields()[11].schema(), other.dept_cod);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.uc_brand)) {
        this.uc_brand = data().deepCopy(fields()[12].schema(), other.uc_brand);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.subnum)) {
        this.subnum = data().deepCopy(fields()[13].schema(), other.subnum);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.dstsub)) {
        this.dstsub = data().deepCopy(fields()[14].schema(), other.dstsub);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.aud_prtnum)) {
        this.aud_prtnum = data().deepCopy(fields()[15].schema(), other.aud_prtnum);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.aud_prt_client_id)) {
        this.aud_prt_client_id = data().deepCopy(fields()[16].schema(), other.aud_prt_client_id);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.audqty)) {
        this.audqty = data().deepCopy(fields()[17].schema(), other.audqty);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.asn_prtnum)) {
        this.asn_prtnum = data().deepCopy(fields()[18].schema(), other.asn_prtnum);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.asn_prt_client_id)) {
        this.asn_prt_client_id = data().deepCopy(fields()[19].schema(), other.asn_prt_client_id);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.asnqty)) {
        this.asnqty = data().deepCopy(fields()[20].schema(), other.asnqty);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.multi_sku_flg)) {
        this.multi_sku_flg = data().deepCopy(fields()[21].schema(), other.multi_sku_flg);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.asn_upd_flg)) {
        this.asn_upd_flg = data().deepCopy(fields()[22].schema(), other.asn_upd_flg);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.appt_id)) {
        this.appt_id = data().deepCopy(fields()[23].schema(), other.appt_id);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.asntotcnt)) {
        this.asntotcnt = data().deepCopy(fields()[24].schema(), other.asntotcnt);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.asnaudcnt)) {
        this.asnaudcnt = data().deepCopy(fields()[25].schema(), other.asnaudcnt);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.asnrvscnt)) {
        this.asnrvscnt = data().deepCopy(fields()[26].schema(), other.asnrvscnt);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.asnflgcnt)) {
        this.asnflgcnt = data().deepCopy(fields()[27].schema(), other.asnflgcnt);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.audthrhbrkflg)) {
        this.audthrhbrkflg = data().deepCopy(fields()[28].schema(), other.audthrhbrkflg);
        fieldSetFlags()[28] = true;
      }
      if (isValidValue(fields()[29], other.audremcnt)) {
        this.audremcnt = data().deepCopy(fields()[29].schema(), other.audremcnt);
        fieldSetFlags()[29] = true;
      }
      if (isValidValue(fields()[30], other.audit_usr_id)) {
        this.audit_usr_id = data().deepCopy(fields()[30].schema(), other.audit_usr_id);
        fieldSetFlags()[30] = true;
      }
      if (isValidValue(fields()[31], other.aud_upc)) {
        this.aud_upc = data().deepCopy(fields()[31].schema(), other.aud_upc);
        fieldSetFlags()[31] = true;
      }
    }

    /**
      * Gets the value of the 'meta_tbnm' field.
      * @return The value.
      */
    public CharSequence getMetaTbnm() {
      return meta_tbnm;
    }

    /**
      * Sets the value of the 'meta_tbnm' field.
      * @param value The value of 'meta_tbnm'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setMetaTbnm(CharSequence value) {
      validate(fields()[0], value);
      this.meta_tbnm = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'meta_tbnm' field has been set.
      * @return True if the 'meta_tbnm' field has been set, false otherwise.
      */
    public boolean hasMetaTbnm() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'meta_tbnm' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearMetaTbnm() {
      meta_tbnm = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'meta_chgtyp' field.
      * @return The value.
      */
    public CharSequence getMetaChgtyp() {
      return meta_chgtyp;
    }

    /**
      * Sets the value of the 'meta_chgtyp' field.
      * @param value The value of 'meta_chgtyp'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setMetaChgtyp(CharSequence value) {
      validate(fields()[1], value);
      this.meta_chgtyp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'meta_chgtyp' field has been set.
      * @return True if the 'meta_chgtyp' field has been set, false otherwise.
      */
    public boolean hasMetaChgtyp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'meta_chgtyp' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearMetaChgtyp() {
      meta_chgtyp = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'meta_chgtm' field.
      * @return The value.
      */
    public CharSequence getMetaChgtm() {
      return meta_chgtm;
    }

    /**
      * Sets the value of the 'meta_chgtm' field.
      * @param value The value of 'meta_chgtm'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setMetaChgtm(CharSequence value) {
      validate(fields()[2], value);
      this.meta_chgtm = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'meta_chgtm' field has been set.
      * @return True if the 'meta_chgtm' field has been set, false otherwise.
      */
    public boolean hasMetaChgtm() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'meta_chgtm' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearMetaChgtm() {
      meta_chgtm = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'audit_log_id' field.
      * @return The value.
      */
    public CharSequence getAuditLogId() {
      return audit_log_id;
    }

    /**
      * Sets the value of the 'audit_log_id' field.
      * @param value The value of 'audit_log_id'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAuditLogId(CharSequence value) {
      validate(fields()[3], value);
      this.audit_log_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'audit_log_id' field has been set.
      * @return True if the 'audit_log_id' field has been set, false otherwise.
      */
    public boolean hasAuditLogId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'audit_log_id' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAuditLogId() {
      audit_log_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'wh_id' field.
      * @return The value.
      */
    public CharSequence getWhId() {
      return wh_id;
    }

    /**
      * Sets the value of the 'wh_id' field.
      * @param value The value of 'wh_id'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setWhId(CharSequence value) {
      validate(fields()[4], value);
      this.wh_id = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'wh_id' field has been set.
      * @return True if the 'wh_id' field has been set, false otherwise.
      */
    public boolean hasWhId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'wh_id' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearWhId() {
      wh_id = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'trndte' field.
      * @return The value.
      */
    public CharSequence getTrndte() {
      return trndte;
    }

    /**
      * Sets the value of the 'trndte' field.
      * @param value The value of 'trndte'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setTrndte(CharSequence value) {
      validate(fields()[5], value);
      this.trndte = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'trndte' field has been set.
      * @return True if the 'trndte' field has been set, false otherwise.
      */
    public boolean hasTrndte() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'trndte' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearTrndte() {
      trndte = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'asnaudtyp' field.
      * @return The value.
      */
    public CharSequence getAsnaudtyp() {
      return asnaudtyp;
    }

    /**
      * Sets the value of the 'asnaudtyp' field.
      * @param value The value of 'asnaudtyp'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAsnaudtyp(CharSequence value) {
      validate(fields()[6], value);
      this.asnaudtyp = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'asnaudtyp' field has been set.
      * @return True if the 'asnaudtyp' field has been set, false otherwise.
      */
    public boolean hasAsnaudtyp() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'asnaudtyp' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAsnaudtyp() {
      asnaudtyp = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'invnum' field.
      * @return The value.
      */
    public CharSequence getInvnum() {
      return invnum;
    }

    /**
      * Sets the value of the 'invnum' field.
      * @param value The value of 'invnum'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setInvnum(CharSequence value) {
      validate(fields()[7], value);
      this.invnum = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'invnum' field has been set.
      * @return True if the 'invnum' field has been set, false otherwise.
      */
    public boolean hasInvnum() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'invnum' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearInvnum() {
      invnum = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'supnum' field.
      * @return The value.
      */
    public CharSequence getSupnum() {
      return supnum;
    }

    /**
      * Sets the value of the 'supnum' field.
      * @param value The value of 'supnum'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setSupnum(CharSequence value) {
      validate(fields()[8], value);
      this.supnum = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'supnum' field has been set.
      * @return True if the 'supnum' field has been set, false otherwise.
      */
    public boolean hasSupnum() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'supnum' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearSupnum() {
      supnum = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'client_id' field.
      * @return The value.
      */
    public CharSequence getClientId() {
      return client_id;
    }

    /**
      * Sets the value of the 'client_id' field.
      * @param value The value of 'client_id'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setClientId(CharSequence value) {
      validate(fields()[9], value);
      this.client_id = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'client_id' field has been set.
      * @return True if the 'client_id' field has been set, false otherwise.
      */
    public boolean hasClientId() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'client_id' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearClientId() {
      client_id = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'trknum' field.
      * @return The value.
      */
    public CharSequence getTrknum() {
      return trknum;
    }

    /**
      * Sets the value of the 'trknum' field.
      * @param value The value of 'trknum'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setTrknum(CharSequence value) {
      validate(fields()[10], value);
      this.trknum = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'trknum' field has been set.
      * @return True if the 'trknum' field has been set, false otherwise.
      */
    public boolean hasTrknum() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'trknum' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearTrknum() {
      trknum = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'dept_cod' field.
      * @return The value.
      */
    public CharSequence getDeptCod() {
      return dept_cod;
    }

    /**
      * Sets the value of the 'dept_cod' field.
      * @param value The value of 'dept_cod'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setDeptCod(CharSequence value) {
      validate(fields()[11], value);
      this.dept_cod = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'dept_cod' field has been set.
      * @return True if the 'dept_cod' field has been set, false otherwise.
      */
    public boolean hasDeptCod() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'dept_cod' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearDeptCod() {
      dept_cod = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'uc_brand' field.
      * @return The value.
      */
    public CharSequence getUcBrand() {
      return uc_brand;
    }

    /**
      * Sets the value of the 'uc_brand' field.
      * @param value The value of 'uc_brand'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setUcBrand(CharSequence value) {
      validate(fields()[12], value);
      this.uc_brand = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'uc_brand' field has been set.
      * @return True if the 'uc_brand' field has been set, false otherwise.
      */
    public boolean hasUcBrand() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'uc_brand' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearUcBrand() {
      uc_brand = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'subnum' field.
      * @return The value.
      */
    public CharSequence getSubnum() {
      return subnum;
    }

    /**
      * Sets the value of the 'subnum' field.
      * @param value The value of 'subnum'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setSubnum(CharSequence value) {
      validate(fields()[13], value);
      this.subnum = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'subnum' field has been set.
      * @return True if the 'subnum' field has been set, false otherwise.
      */
    public boolean hasSubnum() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'subnum' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearSubnum() {
      subnum = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'dstsub' field.
      * @return The value.
      */
    public CharSequence getDstsub() {
      return dstsub;
    }

    /**
      * Sets the value of the 'dstsub' field.
      * @param value The value of 'dstsub'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setDstsub(CharSequence value) {
      validate(fields()[14], value);
      this.dstsub = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'dstsub' field has been set.
      * @return True if the 'dstsub' field has been set, false otherwise.
      */
    public boolean hasDstsub() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'dstsub' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearDstsub() {
      dstsub = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'aud_prtnum' field.
      * @return The value.
      */
    public CharSequence getAudPrtnum() {
      return aud_prtnum;
    }

    /**
      * Sets the value of the 'aud_prtnum' field.
      * @param value The value of 'aud_prtnum'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAudPrtnum(CharSequence value) {
      validate(fields()[15], value);
      this.aud_prtnum = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'aud_prtnum' field has been set.
      * @return True if the 'aud_prtnum' field has been set, false otherwise.
      */
    public boolean hasAudPrtnum() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'aud_prtnum' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAudPrtnum() {
      aud_prtnum = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'aud_prt_client_id' field.
      * @return The value.
      */
    public CharSequence getAudPrtClientId() {
      return aud_prt_client_id;
    }

    /**
      * Sets the value of the 'aud_prt_client_id' field.
      * @param value The value of 'aud_prt_client_id'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAudPrtClientId(CharSequence value) {
      validate(fields()[16], value);
      this.aud_prt_client_id = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'aud_prt_client_id' field has been set.
      * @return True if the 'aud_prt_client_id' field has been set, false otherwise.
      */
    public boolean hasAudPrtClientId() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'aud_prt_client_id' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAudPrtClientId() {
      aud_prt_client_id = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'audqty' field.
      * @return The value.
      */
    public Integer getAudqty() {
      return audqty;
    }

    /**
      * Sets the value of the 'audqty' field.
      * @param value The value of 'audqty'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAudqty(Integer value) {
      validate(fields()[17], value);
      this.audqty = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'audqty' field has been set.
      * @return True if the 'audqty' field has been set, false otherwise.
      */
    public boolean hasAudqty() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'audqty' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAudqty() {
      audqty = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'asn_prtnum' field.
      * @return The value.
      */
    public CharSequence getAsnPrtnum() {
      return asn_prtnum;
    }

    /**
      * Sets the value of the 'asn_prtnum' field.
      * @param value The value of 'asn_prtnum'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAsnPrtnum(CharSequence value) {
      validate(fields()[18], value);
      this.asn_prtnum = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'asn_prtnum' field has been set.
      * @return True if the 'asn_prtnum' field has been set, false otherwise.
      */
    public boolean hasAsnPrtnum() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'asn_prtnum' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAsnPrtnum() {
      asn_prtnum = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'asn_prt_client_id' field.
      * @return The value.
      */
    public CharSequence getAsnPrtClientId() {
      return asn_prt_client_id;
    }

    /**
      * Sets the value of the 'asn_prt_client_id' field.
      * @param value The value of 'asn_prt_client_id'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAsnPrtClientId(CharSequence value) {
      validate(fields()[19], value);
      this.asn_prt_client_id = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'asn_prt_client_id' field has been set.
      * @return True if the 'asn_prt_client_id' field has been set, false otherwise.
      */
    public boolean hasAsnPrtClientId() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'asn_prt_client_id' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAsnPrtClientId() {
      asn_prt_client_id = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'asnqty' field.
      * @return The value.
      */
    public Integer getAsnqty() {
      return asnqty;
    }

    /**
      * Sets the value of the 'asnqty' field.
      * @param value The value of 'asnqty'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAsnqty(Integer value) {
      validate(fields()[20], value);
      this.asnqty = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'asnqty' field has been set.
      * @return True if the 'asnqty' field has been set, false otherwise.
      */
    public boolean hasAsnqty() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'asnqty' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAsnqty() {
      asnqty = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'multi_sku_flg' field.
      * @return The value.
      */
    public Integer getMultiSkuFlg() {
      return multi_sku_flg;
    }

    /**
      * Sets the value of the 'multi_sku_flg' field.
      * @param value The value of 'multi_sku_flg'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setMultiSkuFlg(int value) {
      validate(fields()[21], value);
      this.multi_sku_flg = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'multi_sku_flg' field has been set.
      * @return True if the 'multi_sku_flg' field has been set, false otherwise.
      */
    public boolean hasMultiSkuFlg() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'multi_sku_flg' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearMultiSkuFlg() {
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'asn_upd_flg' field.
      * @return The value.
      */
    public Integer getAsnUpdFlg() {
      return asn_upd_flg;
    }

    /**
      * Sets the value of the 'asn_upd_flg' field.
      * @param value The value of 'asn_upd_flg'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAsnUpdFlg(int value) {
      validate(fields()[22], value);
      this.asn_upd_flg = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'asn_upd_flg' field has been set.
      * @return True if the 'asn_upd_flg' field has been set, false otherwise.
      */
    public boolean hasAsnUpdFlg() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'asn_upd_flg' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAsnUpdFlg() {
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
      * Gets the value of the 'appt_id' field.
      * @return The value.
      */
    public CharSequence getApptId() {
      return appt_id;
    }

    /**
      * Sets the value of the 'appt_id' field.
      * @param value The value of 'appt_id'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setApptId(CharSequence value) {
      validate(fields()[23], value);
      this.appt_id = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
      * Checks whether the 'appt_id' field has been set.
      * @return True if the 'appt_id' field has been set, false otherwise.
      */
    public boolean hasApptId() {
      return fieldSetFlags()[23];
    }


    /**
      * Clears the value of the 'appt_id' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearApptId() {
      appt_id = null;
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
      * Gets the value of the 'asntotcnt' field.
      * @return The value.
      */
    public Integer getAsntotcnt() {
      return asntotcnt;
    }

    /**
      * Sets the value of the 'asntotcnt' field.
      * @param value The value of 'asntotcnt'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAsntotcnt(Integer value) {
      validate(fields()[24], value);
      this.asntotcnt = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
      * Checks whether the 'asntotcnt' field has been set.
      * @return True if the 'asntotcnt' field has been set, false otherwise.
      */
    public boolean hasAsntotcnt() {
      return fieldSetFlags()[24];
    }


    /**
      * Clears the value of the 'asntotcnt' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAsntotcnt() {
      asntotcnt = null;
      fieldSetFlags()[24] = false;
      return this;
    }

    /**
      * Gets the value of the 'asnaudcnt' field.
      * @return The value.
      */
    public Integer getAsnaudcnt() {
      return asnaudcnt;
    }

    /**
      * Sets the value of the 'asnaudcnt' field.
      * @param value The value of 'asnaudcnt'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAsnaudcnt(Integer value) {
      validate(fields()[25], value);
      this.asnaudcnt = value;
      fieldSetFlags()[25] = true;
      return this;
    }

    /**
      * Checks whether the 'asnaudcnt' field has been set.
      * @return True if the 'asnaudcnt' field has been set, false otherwise.
      */
    public boolean hasAsnaudcnt() {
      return fieldSetFlags()[25];
    }


    /**
      * Clears the value of the 'asnaudcnt' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAsnaudcnt() {
      asnaudcnt = null;
      fieldSetFlags()[25] = false;
      return this;
    }

    /**
      * Gets the value of the 'asnrvscnt' field.
      * @return The value.
      */
    public Integer getAsnrvscnt() {
      return asnrvscnt;
    }

    /**
      * Sets the value of the 'asnrvscnt' field.
      * @param value The value of 'asnrvscnt'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAsnrvscnt(Integer value) {
      validate(fields()[26], value);
      this.asnrvscnt = value;
      fieldSetFlags()[26] = true;
      return this;
    }

    /**
      * Checks whether the 'asnrvscnt' field has been set.
      * @return True if the 'asnrvscnt' field has been set, false otherwise.
      */
    public boolean hasAsnrvscnt() {
      return fieldSetFlags()[26];
    }


    /**
      * Clears the value of the 'asnrvscnt' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAsnrvscnt() {
      asnrvscnt = null;
      fieldSetFlags()[26] = false;
      return this;
    }

    /**
      * Gets the value of the 'asnflgcnt' field.
      * @return The value.
      */
    public Integer getAsnflgcnt() {
      return asnflgcnt;
    }

    /**
      * Sets the value of the 'asnflgcnt' field.
      * @param value The value of 'asnflgcnt'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAsnflgcnt(Integer value) {
      validate(fields()[27], value);
      this.asnflgcnt = value;
      fieldSetFlags()[27] = true;
      return this;
    }

    /**
      * Checks whether the 'asnflgcnt' field has been set.
      * @return True if the 'asnflgcnt' field has been set, false otherwise.
      */
    public boolean hasAsnflgcnt() {
      return fieldSetFlags()[27];
    }


    /**
      * Clears the value of the 'asnflgcnt' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAsnflgcnt() {
      asnflgcnt = null;
      fieldSetFlags()[27] = false;
      return this;
    }

    /**
      * Gets the value of the 'audthrhbrkflg' field.
      * @return The value.
      */
    public Integer getAudthrhbrkflg() {
      return audthrhbrkflg;
    }

    /**
      * Sets the value of the 'audthrhbrkflg' field.
      * @param value The value of 'audthrhbrkflg'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAudthrhbrkflg(int value) {
      validate(fields()[28], value);
      this.audthrhbrkflg = value;
      fieldSetFlags()[28] = true;
      return this;
    }

    /**
      * Checks whether the 'audthrhbrkflg' field has been set.
      * @return True if the 'audthrhbrkflg' field has been set, false otherwise.
      */
    public boolean hasAudthrhbrkflg() {
      return fieldSetFlags()[28];
    }


    /**
      * Clears the value of the 'audthrhbrkflg' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAudthrhbrkflg() {
      fieldSetFlags()[28] = false;
      return this;
    }

    /**
      * Gets the value of the 'audremcnt' field.
      * @return The value.
      */
    public Integer getAudremcnt() {
      return audremcnt;
    }

    /**
      * Sets the value of the 'audremcnt' field.
      * @param value The value of 'audremcnt'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAudremcnt(Integer value) {
      validate(fields()[29], value);
      this.audremcnt = value;
      fieldSetFlags()[29] = true;
      return this;
    }

    /**
      * Checks whether the 'audremcnt' field has been set.
      * @return True if the 'audremcnt' field has been set, false otherwise.
      */
    public boolean hasAudremcnt() {
      return fieldSetFlags()[29];
    }


    /**
      * Clears the value of the 'audremcnt' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAudremcnt() {
      audremcnt = null;
      fieldSetFlags()[29] = false;
      return this;
    }

    /**
      * Gets the value of the 'audit_usr_id' field.
      * @return The value.
      */
    public CharSequence getAuditUsrId() {
      return audit_usr_id;
    }

    /**
      * Sets the value of the 'audit_usr_id' field.
      * @param value The value of 'audit_usr_id'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAuditUsrId(CharSequence value) {
      validate(fields()[30], value);
      this.audit_usr_id = value;
      fieldSetFlags()[30] = true;
      return this;
    }

    /**
      * Checks whether the 'audit_usr_id' field has been set.
      * @return True if the 'audit_usr_id' field has been set, false otherwise.
      */
    public boolean hasAuditUsrId() {
      return fieldSetFlags()[30];
    }


    /**
      * Clears the value of the 'audit_usr_id' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAuditUsrId() {
      audit_usr_id = null;
      fieldSetFlags()[30] = false;
      return this;
    }

    /**
      * Gets the value of the 'aud_upc' field.
      * @return The value.
      */
    public CharSequence getAudUpc() {
      return aud_upc;
    }

    /**
      * Sets the value of the 'aud_upc' field.
      * @param value The value of 'aud_upc'.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder setAudUpc(CharSequence value) {
      validate(fields()[31], value);
      this.aud_upc = value;
      fieldSetFlags()[31] = true;
      return this;
    }

    /**
      * Checks whether the 'aud_upc' field has been set.
      * @return True if the 'aud_upc' field has been set, false otherwise.
      */
    public boolean hasAudUpc() {
      return fieldSetFlags()[31];
    }


    /**
      * Clears the value of the 'aud_upc' field.
      * @return This builder.
      */
    public USR_ASN_AUDIT_LOG.Builder clearAudUpc() {
      aud_upc = null;
      fieldSetFlags()[31] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public USR_ASN_AUDIT_LOG build() {
      try {
        USR_ASN_AUDIT_LOG record = new USR_ASN_AUDIT_LOG();
        record.meta_tbnm = fieldSetFlags()[0] ? this.meta_tbnm : (CharSequence) defaultValue(fields()[0]);
        record.meta_chgtyp = fieldSetFlags()[1] ? this.meta_chgtyp : (CharSequence) defaultValue(fields()[1]);
        record.meta_chgtm = fieldSetFlags()[2] ? this.meta_chgtm : (CharSequence) defaultValue(fields()[2]);
        record.audit_log_id = fieldSetFlags()[3] ? this.audit_log_id : (CharSequence) defaultValue(fields()[3]);
        record.wh_id = fieldSetFlags()[4] ? this.wh_id : (CharSequence) defaultValue(fields()[4]);
        record.trndte = fieldSetFlags()[5] ? this.trndte : (CharSequence) defaultValue(fields()[5]);
        record.asnaudtyp = fieldSetFlags()[6] ? this.asnaudtyp : (CharSequence) defaultValue(fields()[6]);
        record.invnum = fieldSetFlags()[7] ? this.invnum : (CharSequence) defaultValue(fields()[7]);
        record.supnum = fieldSetFlags()[8] ? this.supnum : (CharSequence) defaultValue(fields()[8]);
        record.client_id = fieldSetFlags()[9] ? this.client_id : (CharSequence) defaultValue(fields()[9]);
        record.trknum = fieldSetFlags()[10] ? this.trknum : (CharSequence) defaultValue(fields()[10]);
        record.dept_cod = fieldSetFlags()[11] ? this.dept_cod : (CharSequence) defaultValue(fields()[11]);
        record.uc_brand = fieldSetFlags()[12] ? this.uc_brand : (CharSequence) defaultValue(fields()[12]);
        record.subnum = fieldSetFlags()[13] ? this.subnum : (CharSequence) defaultValue(fields()[13]);
        record.dstsub = fieldSetFlags()[14] ? this.dstsub : (CharSequence) defaultValue(fields()[14]);
        record.aud_prtnum = fieldSetFlags()[15] ? this.aud_prtnum : (CharSequence) defaultValue(fields()[15]);
        record.aud_prt_client_id = fieldSetFlags()[16] ? this.aud_prt_client_id : (CharSequence) defaultValue(fields()[16]);
        record.audqty = fieldSetFlags()[17] ? this.audqty : (Integer) defaultValue(fields()[17]);
        record.asn_prtnum = fieldSetFlags()[18] ? this.asn_prtnum : (CharSequence) defaultValue(fields()[18]);
        record.asn_prt_client_id = fieldSetFlags()[19] ? this.asn_prt_client_id : (CharSequence) defaultValue(fields()[19]);
        record.asnqty = fieldSetFlags()[20] ? this.asnqty : (Integer) defaultValue(fields()[20]);
        record.multi_sku_flg = fieldSetFlags()[21] ? this.multi_sku_flg : (Integer) defaultValue(fields()[21]);
        record.asn_upd_flg = fieldSetFlags()[22] ? this.asn_upd_flg : (Integer) defaultValue(fields()[22]);
        record.appt_id = fieldSetFlags()[23] ? this.appt_id : (CharSequence) defaultValue(fields()[23]);
        record.asntotcnt = fieldSetFlags()[24] ? this.asntotcnt : (Integer) defaultValue(fields()[24]);
        record.asnaudcnt = fieldSetFlags()[25] ? this.asnaudcnt : (Integer) defaultValue(fields()[25]);
        record.asnrvscnt = fieldSetFlags()[26] ? this.asnrvscnt : (Integer) defaultValue(fields()[26]);
        record.asnflgcnt = fieldSetFlags()[27] ? this.asnflgcnt : (Integer) defaultValue(fields()[27]);
        record.audthrhbrkflg = fieldSetFlags()[28] ? this.audthrhbrkflg : (Integer) defaultValue(fields()[28]);
        record.audremcnt = fieldSetFlags()[29] ? this.audremcnt : (Integer) defaultValue(fields()[29]);
        record.audit_usr_id = fieldSetFlags()[30] ? this.audit_usr_id : (CharSequence) defaultValue(fields()[30]);
        record.aud_upc = fieldSetFlags()[31] ? this.aud_upc : (CharSequence) defaultValue(fields()[31]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<USR_ASN_AUDIT_LOG>
    WRITER$ = (org.apache.avro.io.DatumWriter<USR_ASN_AUDIT_LOG>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<USR_ASN_AUDIT_LOG>
    READER$ = (org.apache.avro.io.DatumReader<USR_ASN_AUDIT_LOG>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  public static void main(String[] args) {
    System.out.println(SCHEMA$);
  }

}
