version: '2'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    volumes:
      - /Users/artur/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
